import { type RouteConfig, index, route } from "@react-router/dev/routes"

export default [
  route(
    ".well-known/appspecific/com.chrome.devtools.json",
    "routes/well-known.chrome-devtools.tsx"
  ),
  index("routes/landing.tsx"),
  route("login", "routes/login.tsx"),
  route("home", "routes/home.tsx"),
  route("register", "routes/register.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("terms-of-use", "routes/terms-of-use.tsx"),
  route("recover-password", "routes/recover-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("opportunities/opportunity/:id?", "routes/opportunity.tsx"),
  route("opportunities/statuses", "routes/opportunity-statuses.tsx"),
  route("opportunities/status/:id?", "routes/opportunity-status.tsx"),
  route("opportunities", "routes/opportunities.tsx"),
  route("resumes/resume/:id?", "routes/resume.tsx"),
  route("resumes", "routes/resumes.tsx"),
  route("companies/company/:id?", "routes/company.tsx"),
  route("companies", "routes/companies.tsx"),
  route("roles/role/:id?", "routes/role.tsx"),
  route("roles", "routes/roles.tsx"),
  route("skills/skill/:id?", "routes/skill.tsx"),
  route("skills", "routes/skills.tsx"),
  route("languages/language/:id?", "routes/language.tsx"),
  route("languages", "routes/languages.tsx"),
  route("links/link/:id?", "routes/reference-link.tsx"),
  route("links", "routes/links.tsx"),
  route("work-experiences/work-experience/:id?", "routes/work-experience.tsx"),
  route("work-experiences", "routes/work-experiences.tsx"),
  route("certifications/certification/:id?", "routes/certification.tsx"),
  route("certifications", "routes/certifications.tsx"),
  route("educations/education/:id?", "routes/education.tsx"),
  route("educations", "routes/educations.tsx"),
  route("my-data", "routes/my-data.tsx"),
] satisfies RouteConfig
